#ifndef CONFIG_H
#define CONFIG_H

#define MAX_PLANTS 16
#define WATERING_THRESHOLD 35.0f
#define PUMP_DURATION_SEC 6
#define PUMP_COOLDOWN_SEC 60
#define LOOP_DELAY_SEC 2
#define SENSOR_STUCK_COUNT 5
#define SENSOR_STUCK_EPSILON 0.01f
#define SENSOR_FAULT_CLEAR_COUNT 3

#define MAX_ADS1115_BOARDS 4

#endif
